document.getElementById('getKeysButton').onclick = getKeys;

function getKeys() {

var gamecode = /^.*([\w\d]{5})-([\w\d]{5})-([\w\d]{5}).*$/gm; //game keys regex

var replacement = '$1-$2-$3';
var str = document.getElementById('steamkey').value.split('\n');

var i = 0;
var result = "";
for (;i < str.length; i++) {
	if (gamecode.test(str[i]) == true) {
		result += str[i].replace(gamecode, replacement) + "\n";
	}
} //remove everything but game keys

console.log('STEAM GAME CODES:');
console.log(result);
console.log('GENERATED BY STEAM KEY RETRIEVER by /u/absolutezero_01');
document.getElementById('output').value = result;
}

var textarea = document.getElementById('output');
var answer = document.getElementById("copyAnswer");
var copy   = document.getElementById("copyBlock");
copy.addEventListener('click', function(e) {

   textarea.select(); 
   try {
       var successful = document.execCommand('copy');

       if(successful) answer.innerHTML = 'The steam game codes are copied to your clipboard!';
       else answer.innerHTML = 'An error has occured! Try again';
   } catch (err) {
       answer.innerHTML = 'Your browser is not supported! :/';
   }
         setTimeout(function(){
         document.getElementById("copyAnswer").innerHTML="";
         },2250);   
});