document.getElementById('getKeysButton').onclick = getKeys;

function getKeys() {

const gamecode = /^.*([\w\d]{5})-([\w\d]{5})-([\w\d]{5}).*$/gm; //game code regex

const replacement = '$1-$2-$3';
const str = document.getElementById('steamkey').value;

const result = str.replace(gamecode, replacement); //remove everything but game code

console.log('STEAM GAME CODES:');
console.log(result);
console.log('GENERATED BY STEAM KEY RETRIEVER by /u/absolutezero_01');
document.getElementById('output').value = result;
}

var textarea = document.getElementById('output');
var answer = document.getElementById("copyAnswer");
var copy   = document.getElementById("copyBlock");
copy.addEventListener('click', function(e) {

   textarea.select(); 
   try {
       var successful = document.execCommand('copy');

       if(successful) answer.innerHTML = 'The steam game codes are copied to your clipboard!';
       else answer.innerHTML = 'An error has occured! Try again';
   } catch (err) {
       answer.innerHTML = 'Your browser is not supported! :/';
   }
         setTimeout(function(){
         document.getElementById("copyAnswer").innerHTML="";
         },2250);   
});